version: '3'


services:
  db:
    container_name: postgres
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_db
  api:
    build: ./backend
    container_name: api
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80"
    volumes:
      - ./backend/app:/code/app
    ports:
      - "80:80"
    depends_on:
      - db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@admin.org
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5000:80"
    depends_on:
      - db
